name: phpstan

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    name: Build docker image

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: ref
      - uses: nxtlvlsoftware/docker-build-action@master
        with:
          name: docker.pkg.github.com/nxtlvlsoftware/pmmp-php-build/php
          tag: ${{ steps.ref.outputs.branch }}
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}
          registry_uri: ${{ secrets.DOCKER_REGISTRY }}
          pull: false